Add FPGA Timer/CountDownTimer feature
ARMmbed/fpga-ci-test-shield pull request #1
Opened 2019-08-01 10:23 UTC by mprse

This PR adds Verilog implementation for FPGA Timer which can be used in two modes:
- Timer to measure the elapsed time,
- CountDownTimer to generate the programmed delays.

The accuracy of the FPGA Timer is 10 ns: 1 timer tick corresponds to 10 ns.

2019-09-06 13:40 UTC, fkjagodzinski requested changes

2019-09-06 13:40 UTC, fkjagodzinski commented on rtl/timer.v
> +            end else begin
```suggestion
        end else begin
```
Wrong indentation.

2019-09-06 13:40 UTC, fkjagodzinski commented on rtl/timer.v
> +// This module counts elapsed time or perform the delay
```suggestion
// This module counts elapsed time or performs the delay
```

2019-09-06 13:40 UTC, fkjagodzinski commented on rtl/timer.v
> +                    if (enable == 1'b1) begin
Current code increments the counter whenever the `enable` pin is high. This is OK, however I'd like to see a setting that would modify this behavior so the measurement would stop on the first falling edge. This way we could choose to measure the sum of `enable` high states or just the first pulse.

2019-10-02 15:32 UTC, fkjagodzinski commented
Starting CI.

2019-10-18 11:47 UTC, 0xc0170 commented
@mprse Can we proceed to unblock Mbed OS PR ?

2019-10-18 12:23 UTC, mprse commented
> @mprse Can we proceed to unblock Mbed OS PR ?

@fkjagodzinski Are you happy with the last changes?

2019-10-18 12:40 UTC, fkjagodzinski commented
> @fkjagodzinski Are you happy with the last changes?

What changes? Nothing has changed since my review.

2019-10-21 06:25 UTC, mprse commented
> What changes? Nothing has changed since my review.
Sorry, I forgot to push the updates.

I added the requested option, to count only the first pulse.

> @mprse Can we proceed to unblock Mbed OS PR ?
Even with this one is merged. PR https://github.com/ARMmbed/mbed-os/pull/11147 will have to wait for the FPGA-test-shield firmware version update and this is planned next year I think.

2019-10-23 13:43 UTC, 0xc0170 commented
> Even with this one is merged. PR ARMmbed/mbed-os#11147 will have to wait for the FPGA-test-shield firmware version update and this is planned next year I think.

Dang, that is far way. We shall close 11147 and keep in opened in jira as internal ticket  with branch available   to continue this work the next year?

2019-10-24 15:09 UTC, fkjagodzinski approved these changes
Looks good. :+1:

2019-10-24 15:09 UTC, fkjagodzinski commented on rtl/timer.v
> +                end
I found the `count_once_reg` name a bit misleading as I assumed a not-inverted logic here. Consider renaming to something like `counting_enabled`.

2019-10-25 09:22 UTC, mprse commented on rtl/timer.v
> +                end
Fixed

2019-10-28 08:04 UTC, merged